In [45]:
#Problem 1
import numpy as np

a = np.tile(np.arange(7),(7,1))
print(a)
a.shape

[[0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]]


(7, 7)

In [46]:
#Problem 2
from numpy.lib import stride_tricks

A = np.array([1,2,3,4])
print(A)
#Want to produce [[1,2,3],[2,3,4]] 
A.strides
stride_tricks.as_strided(A,shape= (2,3),strides=(8,8))

#Testing a 3x3
test = np.array([1,2,3,4,5])
stride_tricks.as_strided(test, shape = (3,3), strides = (8,8))

[1 2 3 4]


array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [ ]:
#Problem 3
#Stochastic Gradient is better at saving time than standard gradient descent when there exists a large training data.
#This is because instead of running through the entire training data, stochastic gradient only runs through one data point.
#While less accurate, running through enough iterations less than the total training data would provide a good enough estimate.
#Better method would be to use Mini-batch gradient descent where it is a mix of both. 